server {
    server_name papsasinc.com www.papsasinc.com;

    location / {
        proxy_read_timeout 60s;
        proxy_connect_timeout 15s;
        proxy_send_timeout 60s;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /var/www/papsas/staticfiles/;
	autoindex on;
    }

    location /media/ {
        alias /var/www/papsas/media/; 
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/papsasinc.com/fullchain.pem; # managed by Certbot
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    ssl_certificate_key /etc/letsencrypt/live/papsasinc.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.papsasinc.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = papsasinc.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name papsasinc.com www.papsasinc.com;
    return 404; # managed by Certbot




}
