# Generated by Django 5.0.7 on 2024-08-31 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0002_rename_eventdate_event_enddate_event_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.ManyToManyField(null=True, related_name='spectator', to=settings.AUTH_USER_MODEL),
        ),
    ]
