# Generated by Django 5.0.7 on 2024-09-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0004_alter_event_audience_attendance_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='receipt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
