# Generated by Django 5.0.7 on 2024-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0006_remove_event_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
