# Generated by Django 5.0.7 on 2024-09-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0011_membershiptypes_delete_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiptypes',
            name='user',
        ),
        migrations.AddField(
            model_name='membershiptypes',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Special', 'Special'), ('Affliate', 'Affliate'), ('Lifetime', 'Lifetime')], max_length=16, null=True),
        ),
    ]
