# Generated by Django 5.0.7 on 2024-09-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0012_remove_membershiptypes_user_membershiptypes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptypes',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
