# Generated by Django 5.0.7 on 2024-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0013_alter_membershiptypes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptypes',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
