# Generated by Django 5.0.7 on 2024-09-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0014_alter_membershiptypes_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='memType',
        ),
        migrations.AlterField(
            model_name='membershiptypes',
            name='type',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationDate', models.DateField(auto_now_add=True)),
                ('expirationDate', models.DateField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papsas_app.membershiptypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
