# Generated by Django 5.0.7 on 2024-09-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0016_usermembership_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptypes',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
