# Generated by Django 5.0.7 on 2024-09-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0017_membershiptypes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiptypes',
            name='pubmat',
            field=models.ImageField(null=True, upload_to='papsas_app/pubmat/event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pubmat',
            field=models.ImageField(null=True, upload_to='papsas_app/pubmat/event'),
        ),
    ]
