# Generated by Django 5.0.7 on 2024-09-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0018_membershiptypes_pubmat_alter_event_pubmat'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermembership',
            name='verificationID',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/verificationID'),
        ),
    ]
