# Generated by Django 5.0.7 on 2024-09-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0020_usermembership_membershipverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('National Capital Region', 'NCR'), ('Cordillera Administrative Region', 'CAR'), ('Ilocos Region', 'Region I'), ('Cagayan Valley', 'Region II'), ('Central Luzon', 'Region III'), ('Calabarzon', 'Region IV-A'), ('Mimaropa', 'Region IV-B'), ('Bicol Region', 'Region V'), ('Western Visayas', 'Region VI'), ('Central Visayas', 'Region VII'), ('Eastern Visayas', 'Region VIII'), ('Zamboanga Peninsula', 'Region IX'), ('Northern Mindanao', 'Region X'), ('Davao Region', 'Region XI'), ('Soccsksargen', 'Region XII'), ('Caraga', 'Region XIII'), ('Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM')], default='Region', max_length=64),
        ),
    ]
