# Generated by Django 5.0.7 on 2024-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0023_alter_eventregistration_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, default='papsas_app/profilePic/default_dp.jpeg', null=True, upload_to='papsas_app/profilePic'),
        ),
    ]
