# Generated by Django 5.0.7 on 2024-09-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0024_alter_user_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNum',
            field=models.CharField(max_length=11),
        ),
    ]
