# Generated by Django 5.0.7 on 2024-09-15 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0027_alter_attendance_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='candidateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominee', to='papsas_app.candidacy'),
        ),
    ]
