# Generated by Django 5.0.7 on 2024-09-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0028_alter_vote_candidateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='candidateID',
        ),
        migrations.AlterField(
            model_name='vote',
            name='voteDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='candidateID',
            field=models.ManyToManyField(related_name='nominee', to='papsas_app.candidacy'),
        ),
    ]
