# Generated by Django 5.0.7 on 2024-09-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0029_remove_vote_candidateid_alter_vote_votedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='papsas_app.election'),
        ),
    ]
