# Generated by Django 5.0.7 on 2024-09-18 11:51

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0031_alter_event_eventdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=markdownx.models.MarkdownxField(max_length=1048, null=True),
        ),
    ]
