# Generated by Django 5.0.7 on 2024-09-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0032_alter_event_eventdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(max_length=1048, null=True),
        ),
    ]
