# Generated by Django 5.0.7 on 2024-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0034_alter_event_eventdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
