# Generated by Django 5.0.7 on 2024-09-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0035_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
