# Generated by Django 5.0.7 on 2024-09-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0038_achievement_event_poststamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='papsas_app.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(blank=True, default='papsas_app/images/default_dp.jpeg', null=True, upload_to='papsas_app/profilePic'),
        ),
    ]
