# Generated by Django 5.0.7 on 2024-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0039_alter_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='numWinners',
            field=models.IntegerField(null=True),
        ),
    ]
