# Generated by Django 5.0.7 on 2024-09-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0041_newsandoffers_achievement_pubmat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='achievementDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='achievementName',
            new_name='name',
        ),
    ]
