# Generated by Django 5.0.7 on 2024-09-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0042_rename_achievementdescription_achievement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Practitioner', 'Practitioner')], max_length=16),
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='papsas_app.election'),
        ),
    ]
