# Generated by Django 5.0.7 on 2024-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0043_alter_user_occupation_alter_vote_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.CharField(choices=[('Occupation', 'Occupation'), ('Student', 'Student'), ('Practitioner', 'Practitioner')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('Occupation', 'Occupation'), ('Student', 'Student'), ('Practitioner', 'Practitioner')], default='Occupation', max_length=16),
        ),
    ]
