# Generated by Django 5.0.7 on 2024-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0044_event_participant_alter_user_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participant',
        ),
        migrations.AddField(
            model_name='event',
            name='exclusive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Practitioner', 'Practitioner')], default='Occupation', max_length=16),
        ),
    ]
