# Generated by Django 5.0.7 on 2024-09-30 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0045_remove_event_participant_event_exclusive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(18, message='Age must be at least 18.'), django.core.validators.MaxValueValidator(100, message='Age must be less than or equal to 100.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNum',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile number must be 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
