# Generated by Django 5.0.7 on 2024-10-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0046_alter_user_age_alter_user_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
