# Generated by Django 5.0.7 on 2024-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0048_alter_eventregistration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='reference_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermembership',
            name='reference_number',
            field=models.IntegerField(null=True),
        ),
    ]
