# Generated by Django 5.0.7 on 2024-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0049_eventregistration_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsandoffers',
            name='postStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
