# Generated by Django 5.0.7 on 2024-10-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0050_alter_eventregistration_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='pubmat',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/pubmat/achievement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pubmat',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/pubmat/event'),
        ),
        migrations.AlterField(
            model_name='newsandoffers',
            name='pubmat',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/pubmat/newsandoffers'),
        ),
    ]
