# Generated by Django 5.1.2 on 2024-10-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0053_alter_election_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membershipVerification',
        ),
        migrations.AddField(
            model_name='usermembership',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
