# Generated by Django 5.1.2 on 2024-10-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0054_remove_usermembership_membershipverification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='tor',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/tor'),
        ),
    ]
