# Generated by Django 5.1.2 on 2024-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0055_candidacy_tor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidacy',
            name='tor',
        ),
        migrations.AddField(
            model_name='user',
            name='tor',
            field=models.ImageField(blank=True, null=True, upload_to='papsas_app/tor'),
        ),
    ]
