# Generated by Django 5.1.2 on 2024-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0056_remove_candidacy_tor_user_tor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacy',
            name='candidacyStatus',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
