# Generated by Django 5.1.2 on 2024-10-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0058_alter_usermembership_reference_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptypes',
            options={'ordering': ['id']},
        ),
    ]
