# Generated by Django 5.1.2 on 2024-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0060_alter_attendance_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='receipt',
            field=models.ImageField(upload_to='papsas_app/reciept'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='verificationID',
            field=models.ImageField(upload_to='papsas_app/verificationID'),
        ),
    ]
