# Generated by Django 5.1.2 on 2024-11-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0061_alter_user_email_alter_usermembership_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='reference_number',
            field=models.BigIntegerField(),
        ),
    ]
