# Generated by Django 5.1.2 on 2024-11-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0062_alter_usermembership_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='receipt',
            field=models.ImageField(upload_to='papsas_app/reciept'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='reference_number',
            field=models.IntegerField(),
        ),
    ]
