# Generated by Django 5.1.2 on 2024-11-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0066_alter_achievement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'event', 'date_attended')},
        ),
    ]
