# Generated by Django 5.1.2 on 2024-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0067_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
