# Generated by Django 5.1.2 on 2024-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0069_alter_event_options_attendance_next_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(choices=[('Interactive Youth Forum', 'Interactive Youth Forum'), ('National Convention', 'National Convention'), ('National Research Conference', 'National Research Conference')], max_length=255, null=True),
        ),
    ]
