# Generated by Django 5.1.2 on 2024-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0071_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembership',
            name='receipt',
            field=models.ImageField(default='papsas_app/reciept/receipt.png', upload_to='papsas_app/reciept'),
        ),
        migrations.AlterField(
            model_name='usermembership',
            name='verificationID',
            field=models.ImageField(default='papsas_app/verificationID/valid_id.jpg', upload_to='papsas_app/verificationID'),
        ),
    ]
