# Generated by Django 5.1.2 on 2024-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0074_alter_attendance_date_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(null=True),
        ),
    ]
