# Generated by Django 5.1.2 on 2024-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0076_alter_attendance_date_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrating',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrating',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
