# Generated by Django 5.1.2 on 2024-11-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0077_alter_eventrating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(choices=[('Interactive Youth Forum', 'Interactive Youth Forum'), ('National Convention', 'National Convention'), ('National Research Conference', 'National Research Conference'), ('Volunteerism Forum', 'Volunteerism Forum')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventrating',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
