# Generated by Django 5.1.2 on 2024-11-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0078_alter_attendance_date_attended_alter_event_eventname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='credentials',
            field=models.TextField(max_length=9999, null=True),
        ),
    ]
