# Generated by Django 5.1.2 on 2024-11-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0079_candidacy_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='next_location',
            field=models.CharField(blank=True, choices=[('aklan', 'Aklan'), ('palawan', 'Palawan'), ('benguet', 'Benguet'), ('pangasinan', 'Pangasinan'), ('metro_manila', 'Metro Manila'), ('cebu', 'Cebu'), ('davao_del_sur', 'Davao del Sur'), ('pampanga', 'Pampanga'), ('iloilo', 'Iloilo'), ('negros_occidental', 'Negros Occidental'), ('zambales', 'Zambales'), ('cavite', 'Cavite'), ('ilocos_sur', 'Ilocos Sur'), ('la_union', 'La Union'), ('batangas', 'Batangas'), ('camiguin', 'Camiguin'), ('bohol', 'Bohol'), ('misamis_oriental', 'Misamis Oriental'), ('albay', 'Albay'), ('surigao_del_norte', 'Surigao del Norte')], max_length=128, null=True),
        ),
    ]
