# Generated by Django 5.1.2 on 2024-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0080_alter_attendance_next_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
