# Generated by Django 5.1.2 on 2024-11-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0081_alter_attendance_date_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date_attended',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
