# Generated by Django 5.1.2 on 2024-12-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0082_alter_attendance_date_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='pubmat',
            field=models.ImageField(upload_to='papsas_app/pubmat/achievement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pubmat',
            field=models.ImageField(upload_to='papsas_app/pubmat/event'),
        ),
        migrations.AlterField(
            model_name='newsandoffers',
            name='pubmat',
            field=models.ImageField(upload_to='papsas_app/pubmat/newsandoffers'),
        ),
    ]
