# Generated by Django 5.1.2 on 2025-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0084_visitorstats'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='officer',
            constraint=models.UniqueConstraint(fields=('candidateID',), name='unique_officer_per_candidacy'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('election__isnull', False)), fields=('voterID', 'election'), name='unique_vote_per_user_election'),
        ),
    ]
