# Generated by Django 5.1.2 on 2025-10-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0085_officer_unique_officer_per_candidacy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='papsas_app.vote')),
            ],
        ),
    ]
