# Generated by Django 5.1.2 on 2025-11-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0087_candidacy_unique'),
    ]

    operations = [
    ]
