# Generated by Django 5.1.2 on 2025-11-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0088_candidacy_unique_positionless'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='papsas_app.election')),
            ],
            options={
                'ordering': ('sort', 'id'),
                'unique_together': {('election', 'title')},
            },
        ),
    ]
