# Generated by Codex on demand: add Candidacy.position FK to Position
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0089_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='position',
            field=models.ForeignKey(
                to='papsas_app.position',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='candidacies',
            ),
        ),
    ]

