# >>> PAPSAS v1.4 BEGIN
# Generated by hand for conditional unique constraint on Candidacy
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0091_perf_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidacy',
            constraint=models.UniqueConstraint(
                fields=('election', 'position', 'candidate'),
                condition=django.db.models.expressions.Q(('position__isnull', False)),
                name='uniq_candidacy_election_pos_member',
            ),
        ),
    ]
# <<< PAPSAS v1.4 END

