# Generated by Django 5.1.2 on 2025-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papsas_app", "0092_candidacy_unique_pos_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="winners",
            field=models.IntegerField(
                blank=True,
                help_text="Max winners for this position; null means use election-level rule.",
                null=True,
            ),
        ),
    ]
