# Generated by Django 5.1.2 on 2025-11-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0093_position_winners'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidacy',
            name='uq_cand_elec_user_pos',
        ),
        migrations.RemoveIndex(
            model_name='candidacy',
            name='ix_cand_election',
        ),
        migrations.RemoveIndex(
            model_name='candidacy',
            name='ix_cand_position',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='ix_vote_election',
        ),
        migrations.RemoveIndex(
            model_name='voteselection',
            name='ix_vsel_candidate',
        ),
    ]
