# Generated by Django 5.1.2 on 2025-11-05 13:20

from django.db import migrations


def create_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS ix_cand_election "
            "ON papsas_app_candidacy (election_id)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS ix_cand_position "
            "ON papsas_app_candidacy (position_id)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS ix_vsel_candidate "
            "ON papsas_app_voteselection (candidate_id)"
        )
        if vendor == "postgresql":
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS ux_cand_elec_nullpos "
                "ON papsas_app_candidacy (election_id, candidate_id) "
                "WHERE position_id IS NULL"
            )
            cursor.execute(
                "CREATE UNIQUE INDEX IF NOT EXISTS ux_cand_elec_pos "
                "ON papsas_app_candidacy (election_id, position_id, candidate_id) "
                "WHERE position_id IS NOT NULL"
            )


def drop_indexes(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS ix_cand_election")
        cursor.execute("DROP INDEX IF EXISTS ix_cand_position")
        cursor.execute("DROP INDEX IF EXISTS ix_vsel_candidate")
        if vendor == "postgresql":
            cursor.execute("DROP INDEX IF EXISTS ux_cand_elec_nullpos")
            cursor.execute("DROP INDEX IF EXISTS ux_cand_elec_pos")


class Migration(migrations.Migration):

    dependencies = [
        ("papsas_app", "0094_remove_candidacy_uq_cand_elec_user_pos_and_more"),
    ]

    operations = [
        migrations.RunPython(create_indexes, drop_indexes),
    ]
