# Generated by Django 5.1.2 on 2025-11-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papsas_app', '0096_usersecurity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersecurity',
            options={'ordering': ['user_id'], 'verbose_name': 'user security guard', 'verbose_name_plural': 'user security guards'},
        ),
    ]
