# Generated by Django 5.1.2 on 2025-11-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("papsas_app", "0101_devicepushtoken"),
        ("papsas_app", "0101_pagevisit_regionalchapterfeedback"),
    ]

    operations = []
