# Generated by Django 5.1.2 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papsas_app", "0102_merge_20251119_2340"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region_slug",
                    models.CharField(
                        choices=[
                            ("car", "CAR"),
                            ("ncr", "NCR"),
                            ("region-i", "PAPSAS Region I"),
                            ("region-ii", "PAPSAS Region II"),
                            ("region-iii", "PAPSAS Region III"),
                            ("region-iv", "PAPSAS Region IV-A"),
                            ("mimaropa", "PAPSAS MIMAROPA"),
                            ("region-v", "PAPSAS Region V"),
                            ("region-vi", "PAPSAS Region VI"),
                            ("region-vii", "PAPSAS Region VII"),
                            ("region-viii", "PAPSAS Region VIII"),
                            ("nir", "PAPSAS NIR"),
                            ("region-ix", "PAPSAS Region IX"),
                            ("region-x", "PAPSAS Region X"),
                            ("region-xi", "PAPSAS Region XI"),
                            ("region-xii", "PAPSAS Region XII"),
                            ("region-xiii", "PAPSAS Region XIII"),
                            ("barmm", "PAPSAS BARMM"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="papsas_app/regional/posts")),
                ("facebook_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["region_slug", "display_order", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RegionalVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "region_slug",
                    models.CharField(
                        choices=[
                            ("car", "CAR"),
                            ("ncr", "NCR"),
                            ("region-i", "PAPSAS Region I"),
                            ("region-ii", "PAPSAS Region II"),
                            ("region-iii", "PAPSAS Region III"),
                            ("region-iv", "PAPSAS Region IV-A"),
                            ("mimaropa", "PAPSAS MIMAROPA"),
                            ("region-v", "PAPSAS Region V"),
                            ("region-vi", "PAPSAS Region VI"),
                            ("region-vii", "PAPSAS Region VII"),
                            ("region-viii", "PAPSAS Region VIII"),
                            ("nir", "PAPSAS NIR"),
                            ("region-ix", "PAPSAS Region IX"),
                            ("region-x", "PAPSAS Region X"),
                            ("region-xi", "PAPSAS Region XI"),
                            ("region-xii", "PAPSAS Region XII"),
                            ("region-xiii", "PAPSAS Region XIII"),
                            ("barmm", "PAPSAS BARMM"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("caption", models.TextField(blank=True)),
                ("video_type", models.CharField(choices=[("upload", "Upload"), ("embed", "Embed URL")], default="upload", max_length=10)),
                ("video_file", models.FileField(blank=True, null=True, upload_to="papsas_app/regional/videos")),
                ("embed_url", models.URLField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["region_slug", "display_order", "-created_at", "-id"],
            },
        ),
    ]
