# Generated by Django 5.1.2 on 2025-11-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=64)),
                ('scope_election_id', models.IntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='success', max_length=16)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=256)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['action', 'ts'], name='analytics_a_action_323def_idx'), models.Index(fields=['scope_election_id', 'ts'], name='analytics_a_scope_e_5996d3_idx'), models.Index(fields=['actor', 'ts'], name='analytics_a_actor_i_9400ed_idx')],
            },
        ),
    ]
